module Korrvigs.Note
  ( Document (..),
    docMtdt,
    docContent,
    docTitle,
    docRefTo,
    Header (..),
    hdAttr,
    hdTitle,
    hdRefTo,
    hdLevel,
    hdContent,
    hdParent,
    hdDocument,
    Block (..),
    Inline (..),
    Style (..),
    Attr (..),
    attrId,
    attrClasses,
    attrMtdt,
    Cell (..),
    Table (..),
    cellOrig,
    cellWidth,
    cellHeight,
    cellData,
    tableCaption,
    tableCells,
    tableAttr,
    tableHeader,
    tableFooter,
  )
where

import Korrvigs.Note.AST
